build_job:
  image: "gradle:4.7.0-jdk8-alpine"

  stage: build

  variables:
    REPO_ROOT: build/maven2/de/fearnixx/t3serverbot

  script:
  - mkdir -p $REPO_ROOT
  - wget maven.fearnixx.de/de/fearnixx/t3serverbot/maven-metadata.xml -O $REPO_ROOT/maven-metadata.xml
  - wget maven.fearnixx.de/de/fearnixx/t3serverbot/maven-metadata.xml.md5 -O $REPO_ROOT/maven-metadata.xml.md5
  - wget maven.fearnixx.de/de/fearnixx/t3serverbot/maven-metadata.xml.sha1 -O $REPO_ROOT/maven-metadata.xml.sha1
  - gradle build publish

  artifacts:
    paths:
    - ./build/distributions/
    - ./build/maven2/

  only:
  - bleeding

deploy_job:
  image: alpine

  before_script:
  - apk update
  - apk add openssh-client sshpass lftp

  stage: deploy

  script:
  - ls -al
  - echo "pwd" | sshpass -p $SFTP_PASS sftp -P $SFTP_PORT -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST
  - lftp -e "mirror -R ./build/distributions/ htdocs/t3serverbot/dist/" -u $SFTP_USER,$SFTP_PASS sftp://$SFTP_HOST:$SFTP_PORT
  - lftp -e "mirror -R ./build/maven2/ htdocs/" -u $SFTP_USER,$SFTP_PASS sftp://$SFTP_HOST:$SFTP_PORT

  only:
  - bleeding
