pull_request_rules:
  - name: "Automatic merge onto bleeding"
    conditions:
      - "base~=^bleeding-.*"
      - "#approved-reviews-by>=1"
      - "-closed"
      - "-merged"
      - "-label~=breaking"
    actions:
      merge:
        method: "merge"
      delete_head_branch: true
